name: Run Shell Scripts Based on PR Title

on:
  push:
    branches:
      - main  
    
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Determine script to run
        id: script
        shell: bash
        run: |
          if [[ "${{ github.event.head_commit.message }}" == "migrate_restart" ]]; then
            echo "script-file=migrate_and_restart.sh" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.head_commit.message }}" == "migrate" ]]; then
            echo "script-file=migrate.sh" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.head_commit.message }}" == "restart" ]]; then
            echo "script-file=restart.sh" >> $GITHUB_OUTPUT
          else
            echo "script-file=migrate_and_restart.sh" >> $GITHUB_OUTPUT
            exit 1
          fi
      
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 192.168.1.52 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          echo "${{ steps.script.outputs['script-file'] }}"
          ssh -i ~/.ssh/id_rsa navneet@192.168.1.52 'sh /home/ubuntu/DeployScript/$(echo ${{ steps.script.outputs['script-file'] }})'
